# 🧪 Step 2: Evaluate RAG System using RAGAS
This notebook loads the generated testset CSV (`eval_results/testset.csv`), queries your running RAG API to collect search contexts and answers, and evaluates the system's performance using RAGAS metrics.

In [ ]:
!pip install ragas langchain-openai python-dotenv requests datasets pandas tqdm

## ⚙️ Configuration
Edit `PROJECT_ID` and `BASE_URL` to match your running FastAPI instance.

In [4]:
import os
import pandas as pd
from dotenv import load_dotenv

# Load .env from src/.env (go up one level from notebooks/)
load_dotenv(dotenv_path=os.path.join(os.path.dirname(os.getcwd()), 'src', '.env'))

# ── Edit these ──────────────────────────────────────────────
PROJECT_ID = 40
BASE_URL = "http://localhost:5000"
INPUT_PATH = "eval_results/testset.csv"
OUTPUT_PATH = "eval_results/results.csv"
# ────────────────────────────────────────────────────────────

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
assert OPENAI_API_KEY, "OPENAI_API_KEY not found in src/.env!"

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
assert GROQ_API_KEY, "GROQ_API_KEY not found in src/.env!"

print(f"✅ Config loaded. Project ID: {PROJECT_ID}")

✅ Config loaded. Project ID: 40

## 📥 Step 1: Load Testset
We load the Q&A dataset generated in Step 1.

In [5]:
df_testset = pd.read_csv(INPUT_PATH)
print(f"✅ Loaded {len(df_testset)} test cases.")
df_testset.head(3)

✅ Loaded 54 test cases.

,user_input,reference,reference_contexts
0,What types of data sources are covered in the ...,The learning material covers working with data...,explains the solution and provides meaningful ...
1,How long has O'Reilly Media been providing tec...,O'Reilly Media has provided technology and bus...,explains the solution and provides meaningful ...
2,When was the second edition of the book released?,The second edition of the book was released in...,"Preface\nxiii Of course, the machine learning ..."

## ⚙️ Step 2: Query RAG Backend to Collect Output
For each question, we query the FastAPI backend:
1. `POST /api/v1/nlp/index/search/{project_id}` to get retrieved chunks (context)
2. `POST /api/v1/nlp/index/answer/{project_id}` to get the generated answer

In [6]:
import requests
from tqdm.auto import tqdm

eval_data = []

for idx, row in tqdm(df_testset.iterrows(), total=len(df_testset), desc="Querying RAG system"):
    question = row["user_input"]
    reference = row["reference"]
    
    # 1. Retrieve contexts from the search endpoint
    search_resp = requests.post(
        f"{BASE_URL}/api/v1/nlp/index/search/{PROJECT_ID}",
        json={"text": question, "limit": 5}
    )
    if search_resp.status_code != 200:
        print(f"⚠️ Search failed for: '{question[:30]}...' -> HTTP {search_resp.status_code}")
        continue
    
    search_results = search_resp.json().get("results", [])
    contexts = [r.get("text", "") for r in search_results]
    
    # 2. Get RAG answer from the answer endpoint
    answer_resp = requests.post(
        f"{BASE_URL}/api/v1/nlp/index/answer/{PROJECT_ID}",
        json={"text": question, "limit": 5}
    )
    if answer_resp.status_code != 200:
        print(f"⚠️ Answer generation failed for: '{question[:30]}...' -> HTTP {answer_resp.status_code}")
        continue
        
    answer = answer_resp.json().get("answer", "")
    
    eval_data.append({
        "question": question,
        "contexts": contexts,
        "answer": answer,
        "ground_truth": reference
    })

print(f"✅ Collected RAG responses for {len(eval_data)} questions.")

Querying RAG system: 100%|██████████| 54/54 [02:24<00:00,  2.67s/it]

✅ Collected RAG responses for 54 questions.

## 📊 Step 3: Run RAGAS Evaluation
We wrap our OpenAI model using Ragas wrappers and run the evaluation on the collected dataset.

In [8]:
from langchain_openai import ChatOpenAI

# Add your Groq API keys here (create free accounts at console.groq.com)
GROQ_API_KEYS = [
    "gsk_REDACTED_KEY",
    "gsk_REDACTED_KEY",
    "gsk_REDACTED_KEY",
    "gsk_REDACTED_KEY",
    "gsk_REDACTED_KEY",
    "gsk_REDACTED_KEY",
    "gsk_REDACTED_KEY",
    # Add as many as you want
]

# Pre-create one client per key
_clients = [
    ChatOpenAI(
        model="llama-3.3-70b-versatile",
        api_key=key,
        base_url="https://api.groq.com/openai/v1",
    )
    for key in GROQ_API_KEYS
]
_state = {"idx": 0}

class RotatingGroqLLM(ChatOpenAI):
    """Auto-rotates to the next API key on rate limit errors."""

    async def _agenerate(self, messages, stop=None, run_manager=None, **kwargs):
        kwargs["n"] = 1
        tried = 0
        while tried < len(_clients):
            try:
                return await _clients[_state["idx"]]._agenerate(
                    messages, stop=stop, run_manager=run_manager, **kwargs
                )
            except Exception as e:
                if "429" in str(e) or "rate_limit" in str(e).lower():
                    old = _state["idx"] + 1
                    _state["idx"] = (_state["idx"] + 1) % len(_clients)
                    print(f"🔄 Key #{old} rate limited → switching to key #{_state['idx']+1}/{len(_clients)}")
                    tried += 1
                else:
                    raise
        raise Exception("❌ All API keys exhausted!")

    def _generate(self, messages, stop=None, run_manager=None, **kwargs):
        kwargs["n"] = 1
        tried = 0
        while tried < len(_clients):
            try:
                return _clients[_state["idx"]]._generate(
                    messages, stop=stop, run_manager=run_manager, **kwargs
                )
            except Exception as e:
                if "429" in str(e) or "rate_limit" in str(e).lower():
                    old = _state["idx"] + 1
                    _state["idx"] = (_state["idx"] + 1) % len(_clients)
                    print(f"🔄 Key #{old} rate limited → switching to key #{_state['idx']+1}/{len(_clients)}")
                    tried += 1
                else:
                    raise
        raise Exception("❌ All API keys exhausted!")

print(f"✅ {len(GROQ_API_KEYS)} Groq API keys loaded and ready to rotate")

✅ 7 Groq API keys loaded and ready to rotate

In [9]:
from datasets import Dataset
from ragas import evaluate
from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall
)
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_openai import OpenAIEmbeddings

dataset = Dataset.from_dict({
    "question": [x["question"] for x in eval_data],
    "contexts": [x["contexts"] for x in eval_data],
    "answer": [x["answer"] for x in eval_data],
    "ground_truth": [x["ground_truth"] for x in eval_data]
})

# Uses the rotating key pool defined above
lc_llm = RotatingGroqLLM(
    model="llama-3.3-70b-versatile",
    api_key=GROQ_API_KEYS[0],
    base_url="https://api.groq.com/openai/v1",
)
lc_embeddings = OpenAIEmbeddings(model="text-embedding-3-small", api_key=OPENAI_API_KEY, chunk_size=8)

evaluator_llm = LangchainLLMWrapper(lc_llm)
evaluator_embeddings = LangchainEmbeddingsWrapper(lc_embeddings)

print("🚀 Running RAGAS evaluation...")
result = evaluate(
    dataset=dataset,
    metrics=[faithfulness, answer_relevancy, context_precision, context_recall],
    llm=evaluator_llm,
    embeddings=evaluator_embeddings,
    raise_exceptions=False,
)

print("\n✅ Evaluation Completed!")
print(result)

/tmp/ipykernel_218445/3914410752.py:3: DeprecationWarning: Importing faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import faithfulness
  from ragas.metrics import (
/tmp/ipykernel_218445/3914410752.py:3: DeprecationWarning: Importing answer_relevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import answer_relevancy
  from ragas.metrics import (
/tmp/ipykernel_218445/3914410752.py:3: DeprecationWarning: Importing context_precision from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_precision
  from ragas.metrics import (
/tmp/ipykernel_218445/3914410752.py:3: DeprecationWarning: Importing context_recall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_recall
  from ragas.metrics import (
/tmp/ipykernel_218445/3914410752.py:28: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  evaluator_llm = LangchainLLMWrapper(lc_llm)
/tmp/ipykernel_218445/3914410752.py:29: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  evaluator_embeddings = LangchainEmbeddingsWrapper(lc_embeddings)

🚀 Running RAGAS evaluation...

Evaluating:   0%|          | 0/216 [00:00<?, ?it/s]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   0%|          | 1/216 [00:02<09:22,  2.62s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   1%|          | 2/216 [00:07<14:20,  4.02s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   4%|▍         | 9/216 [00:11<03:32,  1.03s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   5%|▍         | 10/216 [00:12<03:42,  1.08s/it]

🔄 Key #1 rate limited → switching to key #2/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   5%|▌         | 11/216 [00:17<05:49,  1.70s/it]

🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7

Evaluating:   6%|▌         | 12/216 [00:22<08:13,  2.42s/it]

🔄 Key #1 rate limited → switching to key #2/7

Evaluating:   7%|▋         | 16/216 [00:23<03:27,  1.04s/it]

🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   9%|▉         | 19/216 [00:30<05:21,  1.63s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   9%|▉         | 20/216 [00:31<04:50,  1.48s/it]

🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7

Evaluating:  10%|▉         | 21/216 [00:32<03:57,  1.22s/it]

🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7

Evaluating:  11%|█         | 23/216 [00:36<04:36,  1.43s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.

🔄 Key #6 rate limited → switching to key #7/7

Evaluating:  12%|█▏        | 25/216 [00:37<03:18,  1.04s/it]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7

Evaluating:  12%|█▏        | 26/216 [00:38<02:45,  1.15it/s]

🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7

Evaluating:  13%|█▎        | 28/216 [00:43<06:32,  2.09s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.

🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7

Evaluating:  15%|█▍        | 32/216 [00:47<03:48,  1.24s/it]

🔄 Key #3 rate limited → switching to key #4/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  15%|█▌        | 33/216 [00:49<04:16,  1.40s/it]

🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  17%|█▋        | 37/216 [00:51<02:21,  1.27it/s]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  18%|█▊        | 39/216 [00:53<02:27,  1.20it/s]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7

Evaluating:  19%|█▉        | 41/216 [00:55<02:49,  1.03it/s]

🔄 Key #6 rate limited → switching to key #7/7

Evaluating:  19%|█▉        | 42/216 [00:56<02:30,  1.16it/s]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  20%|██        | 44/216 [00:58<02:35,  1.11it/s]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7

Evaluating:  21%|██        | 45/216 [01:06<08:02,  2.82s/it]

🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7

Evaluating:  21%|██▏       | 46/216 [01:09<08:05,  2.85s/it]

🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  22%|██▏       | 48/216 [01:10<04:53,  1.75s/it]

🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7

Evaluating:  23%|██▎       | 49/216 [01:12<05:22,  1.93s/it]

🔄 Key #1 rate limited → switching to key #2/7

Evaluating:  23%|██▎       | 50/216 [01:14<05:14,  1.89s/it]

🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7

Evaluating:  24%|██▎       | 51/216 [01:18<06:25,  2.34s/it]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  24%|██▍       | 52/216 [01:20<06:20,  2.32s/it]

🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7

Evaluating:  25%|██▍       | 53/216 [01:21<05:08,  1.90s/it]

🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7

Evaluating:  25%|██▌       | 54/216 [01:23<05:04,  1.88s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  25%|██▌       | 55/216 [01:24<04:30,  1.68s/it]

🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7

Evaluating:  26%|██▌       | 56/216 [01:29<07:05,  2.66s/it]

🔄 Key #2 rate limited → switching to key #3/7

Evaluating:  26%|██▋       | 57/216 [01:30<05:48,  2.19s/it]

🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7

Evaluating:  27%|██▋       | 59/216 [01:34<05:07,  1.96s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  28%|██▊       | 60/216 [01:36<04:42,  1.81s/it]

🔄 Key #6 rate limited → switching to key #7/7

Evaluating:  28%|██▊       | 61/216 [01:37<04:09,  1.61s/it]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7

Evaluating:  29%|██▉       | 63/216 [01:43<05:33,  2.18s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.

🔄 Key #6 rate limited → switching to key #7/7

Evaluating:  30%|██▉       | 64/216 [01:44<04:35,  1.81s/it]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7

Evaluating:  30%|███       | 65/216 [01:52<08:45,  3.48s/it]

🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7

Evaluating:  31%|███       | 66/216 [01:55<08:58,  3.59s/it]

🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  31%|███▏      | 68/216 [01:59<06:18,  2.56s/it]

🔄 Key #1 rate limited → switching to key #2/7

Exception raised in Job[59]: Exception(❌ All API keys exhausted!)
Evaluating:  32%|███▏      | 69/216 [02:00<04:52,  1.99s/it]

🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7

Exception raised in Job[56]: Exception(❌ All API keys exhausted!)
Evaluating:  32%|███▏      | 70/216 [02:02<05:09,  2.12s/it]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  33%|███▎      | 71/216 [02:03<04:26,  1.84s/it]Exception raised in Job[48]: Exception(❌ All API keys exhausted!)
Evaluating:  33%|███▎      | 72/216 [02:04<03:24,  1.42s/it]

🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7

Exception raised in Job[63]: Exception(❌ All API keys exhausted!)
Evaluating:  34%|███▍      | 73/216 [02:05<03:26,  1.44s/it]

🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7

Exception raised in Job[60]: Exception(❌ All API keys exhausted!)
Evaluating:  34%|███▍      | 74/216 [02:07<03:27,  1.46s/it]

🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7

Evaluating:  36%|███▌      | 77/216 [02:11<03:00,  1.30s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  37%|███▋      | 79/216 [02:12<02:11,  1.04it/s]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  37%|███▋      | 80/216 [02:13<02:03,  1.10it/s]

🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7

Evaluating:  38%|███▊      | 81/216 [02:16<03:05,  1.37s/it]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7

Evaluating:  38%|███▊      | 82/216 [02:17<02:40,  1.20s/it]

🔄 Key #2 rate limited → switching to key #3/7

Evaluating:  38%|███▊      | 83/216 [02:17<02:01,  1.09it/s]

🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  39%|███▉      | 84/216 [02:20<03:29,  1.59s/it]

🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7

Evaluating:  40%|███▉      | 86/216 [02:28<05:31,  2.55s/it]

🔄 Key #1 rate limited → switching to key #2/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.

🔄 Key #2 rate limited → switching to key #3/7

Evaluating:  40%|████      | 87/216 [02:32<06:09,  2.86s/it]

🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7

Evaluating:  41%|████      | 88/216 [02:33<05:12,  2.44s/it]

🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7

Evaluating:  42%|████▏     | 91/216 [02:41<04:33,  2.19s/it]

🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7

Exception raised in Job[82]: Exception(❌ All API keys exhausted!)
Evaluating:  43%|████▎     | 92/216 [02:46<05:59,  2.90s/it]

🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7

Evaluating:  43%|████▎     | 93/216 [02:46<04:32,  2.22s/it]

🔄 Key #7 rate limited → switching to key #1/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  44%|████▎     | 94/216 [02:49<04:39,  2.29s/it]Exception raised in Job[76]: Exception(❌ All API keys exhausted!)
Evaluating:  44%|████▍     | 95/216 [02:49<03:29,  1.73s/it]

🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  44%|████▍     | 96/216 [02:51<03:12,  1.60s/it]

🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7

Evaluating:  45%|████▍     | 97/216 [02:52<03:01,  1.53s/it]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7

Evaluating:  45%|████▌     | 98/216 [02:56<04:27,  2.27s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  46%|████▌     | 99/216 [02:57<03:59,  2.04s/it]

🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7

Evaluating:  47%|████▋     | 101/216 [02:59<02:40,  1.39s/it]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7

Exception raised in Job[79]: Exception(❌ All API keys exhausted!)
Evaluating:  47%|████▋     | 102/216 [03:04<04:30,  2.38s/it]

🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  48%|████▊     | 103/216 [03:10<06:19,  3.36s/it]

🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7

Evaluating:  48%|████▊     | 104/216 [03:15<07:14,  3.88s/it]Exception raised in Job[91]: Exception(❌ All API keys exhausted!)

🔄 Key #5 rate limited → switching to key #6/7

Evaluating:  50%|████▉     | 107/216 [03:16<03:40,  2.02s/it]

🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7

Evaluating:  50%|█████     | 108/216 [03:22<04:52,  2.70s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  50%|█████     | 109/216 [03:31<07:36,  4.26s/it]

🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7

Evaluating:  51%|█████▏    | 111/216 [03:33<05:20,  3.05s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  52%|█████▏    | 112/216 [03:53<11:26,  6.60s/it]

🔄 Key #3 rate limited → switching to key #4/7

Evaluating:  54%|█████▍    | 117/216 [03:53<04:16,  2.59s/it]

🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.

🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7

Evaluating:  55%|█████▌    | 119/216 [03:55<03:30,  2.17s/it]

🔄 Key #7 rate limited → switching to key #1/7

Evaluating:  57%|█████▋    | 123/216 [03:57<02:13,  1.44s/it]

🔄 Key #1 rate limited → switching to key #2/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  57%|█████▋    | 124/216 [04:01<02:48,  1.83s/it]

🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  58%|█████▊    | 126/216 [04:03<02:15,  1.50s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.

🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7

Evaluating:  59%|█████▉    | 127/216 [04:04<02:10,  1.47s/it]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7

Evaluating:  59%|█████▉    | 128/216 [04:06<02:13,  1.51s/it]

🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7

Evaluating:  60%|██████    | 130/216 [04:09<02:05,  1.46s/it]

🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7

Evaluating:  61%|██████    | 131/216 [04:17<04:33,  3.22s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.

🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7

Evaluating:  62%|██████▏   | 133/216 [04:18<02:42,  1.96s/it]

🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7

Evaluating:  62%|██████▏   | 134/216 [04:19<02:18,  1.68s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  62%|██████▎   | 135/216 [04:20<01:59,  1.48s/it]

🔄 Key #6 rate limited → switching to key #7/7

Evaluating:  63%|██████▎   | 136/216 [04:24<02:59,  2.24s/it]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7

Evaluating:  63%|██████▎   | 137/216 [04:32<05:12,  3.95s/it]

🔄 Key #5 rate limited → switching to key #6/7

Evaluating:  64%|██████▍   | 138/216 [04:42<07:24,  5.69s/it]

🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7

Evaluating:  65%|██████▍   | 140/216 [05:05<10:09,  8.02s/it]

🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  66%|██████▌   | 143/216 [05:06<04:32,  3.74s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  69%|██████▊   | 148/216 [05:08<01:43,  1.52s/it]

🔄 Key #7 rate limited → switching to key #1/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  70%|██████▉   | 151/216 [05:14<01:50,  1.70s/it]

🔄 Key #1 rate limited → switching to key #2/7

Evaluating:  70%|███████   | 152/216 [05:15<01:37,  1.52s/it]

🔄 Key #2 rate limited → switching to key #3/7

Evaluating:  71%|███████   | 153/216 [05:16<01:29,  1.42s/it]

🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7

Evaluating:  71%|███████▏  | 154/216 [05:18<01:28,  1.43s/it]

🔄 Key #6 rate limited → switching to key #7/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  72%|███████▏  | 156/216 [05:19<01:03,  1.06s/it]

🔄 Key #7 rate limited → switching to key #1/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  73%|███████▎  | 157/216 [05:22<01:29,  1.52s/it]

🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7

Evaluating:  74%|███████▎  | 159/216 [05:26<01:31,  1.60s/it]

🔄 Key #6 rate limited → switching to key #7/7

Evaluating:  74%|███████▍  | 160/216 [05:26<01:13,  1.31s/it]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  75%|███████▌  | 162/216 [05:35<02:08,  2.39s/it]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7

Evaluating:  75%|███████▌  | 163/216 [05:37<02:03,  2.33s/it]

🔄 Key #6 rate limited → switching to key #7/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  76%|███████▌  | 164/216 [05:51<05:04,  5.86s/it]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7

Evaluating:  77%|███████▋  | 167/216 [05:55<02:29,  3.05s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  78%|███████▊  | 168/216 [05:56<02:01,  2.54s/it]

🔄 Key #2 rate limited → switching to key #3/7

Evaluating:  79%|███████▊  | 170/216 [05:59<01:41,  2.21s/it]

🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7

Evaluating:  79%|███████▉  | 171/216 [06:00<01:23,  1.86s/it]

🔄 Key #7 rate limited → switching to key #1/7

Evaluating:  80%|███████▉  | 172/216 [06:01<01:11,  1.63s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  81%|████████  | 174/216 [06:03<00:51,  1.22s/it]

🔄 Key #1 rate limited → switching to key #2/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  81%|████████  | 175/216 [06:05<01:01,  1.50s/it]

🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7

Evaluating:  82%|████████▏ | 177/216 [06:06<00:43,  1.11s/it]

🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7

Evaluating:  82%|████████▏ | 178/216 [06:12<01:26,  2.28s/it]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  83%|████████▎ | 179/216 [06:16<01:45,  2.85s/it]

🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7

Evaluating:  84%|████████▍ | 181/216 [06:18<01:01,  1.76s/it]

🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7

Evaluating:  84%|████████▍ | 182/216 [06:20<01:10,  2.08s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  85%|████████▍ | 183/216 [06:22<01:03,  1.93s/it]

🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7

Evaluating:  86%|████████▌ | 185/216 [06:23<00:35,  1.14s/it]

🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7

Evaluating:  87%|████████▋ | 187/216 [06:32<01:09,  2.40s/it]

🔄 Key #5 rate limited → switching to key #6/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  88%|████████▊ | 189/216 [06:36<00:58,  2.18s/it]

🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7

Evaluating:  88%|████████▊ | 191/216 [06:55<02:13,  5.34s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  89%|████████▉ | 192/216 [07:14<03:50,  9.59s/it]

🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7

Evaluating:  90%|█████████ | 195/216 [07:22<01:45,  5.01s/it]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  92%|█████████▏| 199/216 [07:26<00:45,  2.70s/it]

🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7

LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  93%|█████████▎| 200/216 [07:30<00:46,  2.88s/it]

🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7

Evaluating:  95%|█████████▍| 205/216 [07:32<00:16,  1.54s/it]

🔄 Key #5 rate limited → switching to key #6/7

Evaluating:  96%|█████████▋| 208/216 [07:41<00:15,  1.94s/it]

🔄 Key #6 rate limited → switching to key #7/7

Evaluating:  97%|█████████▋| 210/216 [07:42<00:09,  1.51s/it]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7

Evaluating:  98%|█████████▊| 211/216 [07:45<00:08,  1.69s/it]

🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7

Exception raised in Job[214]: Exception(❌ All API keys exhausted!)
Evaluating:  98%|█████████▊| 212/216 [07:45<00:05,  1.46s/it]

🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7
🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7
🔄 Key #7 rate limited → switching to key #1/7

Exception raised in Job[210]: Exception(❌ All API keys exhausted!)
Evaluating:  99%|█████████▊| 213/216 [07:45<00:03,  1.17s/it]

🔄 Key #1 rate limited → switching to key #2/7
🔄 Key #2 rate limited → switching to key #3/7
🔄 Key #3 rate limited → switching to key #4/7
🔄 Key #4 rate limited → switching to key #5/7

Exception raised in Job[182]: Exception(❌ All API keys exhausted!)
Evaluating:  99%|█████████▉| 214/216 [07:46<00:01,  1.03it/s]

🔄 Key #5 rate limited → switching to key #6/7
🔄 Key #6 rate limited → switching to key #7/7

Evaluating: 100%|█████████▉| 215/216 [07:47<00:00,  1.05it/s]Exception raised in Job[211]: Exception(❌ All API keys exhausted!)
Evaluating: 100%|██████████| 216/216 [07:47<00:00,  2.16s/it]

🔄 Key #7 rate limited → switching to key #1/7
🔄 Key #1 rate limited → switching to key #2/7

✅ Evaluation Completed!
{'faithfulness': 0.8936, 'answer_relevancy': 0.8387, 'context_precision': 0.8758, 'context_recall': 0.9286}

## 💾 Step 4: Save and Display Results
We convert the evaluation results into a pandas DataFrame, format them nicely, and save them to a CSV file.

In [11]:
import os
import pandas as pd

df_results = result.to_pandas()

os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
df_results.to_csv(OUTPUT_PATH, index=False)
print(f"✅ Results saved to {OUTPUT_PATH}")

# Show actual column names first
print(f"Columns: {list(df_results.columns)}")

pd.set_option('display.max_colwidth', 100)
df_results[["user_input", "faithfulness", "answer_relevancy", "context_precision", "context_recall"]]

✅ Results saved to eval_results/results.csv
Columns: ['user_input', 'retrieved_contexts', 'response', 'reference', 'faithfulness', 'answer_relevancy', 'context_precision', 'context_recall']

,user_input,faithfulness,answer_relevancy,context_precision,context_recall
0,What types of data sources are covered in the provided learning material?,1.000000,0.783129,0.333333,1.0
1,How long has O'Reilly Media been providing technology and business training?,1.000000,0.984417,1.000000,1.0
2,When was the second edition of the book released?,1.000000,0.957246,1.000000,1.0
3,"What is the purpose of using pretrained classifiers in machine learning pipelines, as introduced...",1.000000,0.842709,1.000000,1.0
4,What are the two preprocessing steps contained in the preprocess object?,1.000000,0.950121,1.000000,1.0
5,"What type of machine learning is discussed in much of the book, where access to both features an...",1.000000,0.533176,0.805556,1.0
6,What is the purpose of the chi-square (χ²) statistic in the context of this book?,1.000000,0.689458,0.679167,1.0
7,Why was the second edition of this book easier to create for the first author?,1.000000,0.957273,1.000000,1.0
8,"What typographical convention is used in the book to indicate new terms, URLs, email addresses, ...",0.500000,0.469461,1.000000,1.0
9,How is the issue of imbalanced classes handled in the context of categorical data?,1.000000,0.000000,0.000000,0.0
10,What technique is used to determine the importance of words in a document?,0.500000,0.717423,1.000000,1.0
11,"How can a pretrained model be utilized for a specific task, such as predicting whether an email ...",1.000000,0.746249,1.000000,1.0
12,What is the purpose of finding the hyperplane in support vector machines?,NaN,1.000000,1.000000,1.0
13,What are the two major weaknesses of a model evaluation approach that is not using k-fold cross-...,1.000000,0.957986,1.000000,1.0
14,What method does IVF use to partition the search space into distinct areas?,NaN,0.924540,1.000000,NaN
15,"Why is collecting more observations, especially from the minority class, considered the best str...",NaN,0.459492,1.000000,NaN
16,What should be considered when deciding how to handle outliers in a dataset?,1.000000,0.969383,1.000000,1.0
17,What is the primary goal of model evaluation in machine learning?,1.000000,0.874040,1.000000,1.0
18,What does the F1 metric represent in the context of model evaluation?,1.000000,0.776766,1.000000,1.0
19,How do individuals move in the analogy of the foggy football field?,NaN,0.780192,1.000000,NaN
20,What strategy is recommended for detecting outliers?,1.000000,0.981753,NaN,1.0
21,How can we speed up the process of training multiple models in scikit-learn?,0.714286,0.975770,1.000000,1.0
22,What was the range of principal components considered in the search space for the model selection?,0.714286,0.778822,1.000000,NaN
23,How was the performance of the model evaluated during k-fold cross-validation?,1.000000,0.742937,0.477778,1.0
24,What is the purpose of the scoring parameter in the provided code snippet?,0.500000,0.714614,1.000000,1.0
25,How can you determine the number of best features to keep after conducting Recursive Feature Eli...,1.000000,0.927257,1.000000,1.0
26,What is the purpose of saving a trained model?,0.625000,1.000000,1.000000,1.0
27,How can the number of features be reduced using feature selection?,0.842105,0.673443,1.000000,1.0
28,What is the primary goal when creating models?,0.833333,1.000000,1.000000,1.0
29,What is one downside of the feature extraction techniques discussed?,1.000000,0.850570,1.000000,1.0
30,What is the purpose of splitting observations into training and test sets in validation?,0.833333,1.000000,0.679167,1.0
31,What are some examples of use cases that have become increasingly commoditized with the growth o...,0.928571,0.972471,0.750000,1.0
32,How is the autograd feature utilized in PyTorch?,0.800000,0.873465,0.679167,0.0
33,What is the purpose of the to_datetime method in the pandas library?,0.800000,0.974454,1.000000,1.0
34,What class is used to define a simple neural network architecture in PyTorch?,1.000000,0.863805,0.950000,1.0
35,What is involved in constructing a feedforward neural network in PyTorch?,0.827586,0.940078,1.000000,1.0
36,What is the purpose of edge detection in image processing?,0.250000,0.825667,0.750000,1.0
37,Why might the price of mansions with over 100 bathrooms be driven by a different dynamic than re...,1.000000,0.761588,0.950000,1.0
38,What is the potential drawback of standardizing images by resizing them?,1.000000,0.779021,0.916667,1.0
39,What type of metrics can be used to evaluate the performance of a classifier with more than two ...,1.000000,0.889680,0.916667,1.0
40,What is the purpose of using make_scorer in scikit-learn?,1.000000,0.939603,0.887500,1.0
41,What does the R2 regression evaluation metric measure?,1.000000,0.726150,1.000000,1.0
42,What is the formal definition of Mean Squared Error (MSE) in the context of regression models?,1.000000,0.828004,0.533333,1.0
43,How can you evaluate the quality of a trained classification model using scikit-learn?,1.000000,0.896975,0.950000,0.5
44,What is recommended to use instead of the development server for a production deployment?,1.000000,0.704339,0.000000,1.0
45,How can you serve your trained TensorFlow model using a web server?,0.941176,0.982070,NaN,1.0
46,What method name is used for serving TensorFlow models?,1.000000,0.985052,0.750000,1.0
47,On which port is the REST gunicorn microservice running?,1.000000,1.000000,1.000000,1.0
48,"What method can be used to reduce overfitting of data in a neural network, and what are the tech...",1.000000,0.879876,1.000000,1.0
49,"How does scikit-learn's MeanShift implementation assign people to clusters, and what is the end ...",0.833333,0.721972,0.866667,0.0
50,What is the purpose of reducing the number of features in data using feature extraction techniques?,0.571429,0.976801,0.916667,1.0
51,What happens to the weight wi when a weak model predicts xi correctly?,1.000000,0.913001,1.000000,1.0
52,"What does the term frequency, or tf, measure in a document?",1.000000,0.980085,NaN,NaN
53,Why is torch.no_grad() used when evaluating a network?,0.666667,0.859005,NaN,1.0

# 📊 RAG Evaluation Metrics (RAGAS)

To evaluate the performance of our Retrieval-Augmented Generation (RAG) system, we use four key metrics from the **RAGAS** framework. These metrics assess the two main components of the pipeline: **Retrieval** (finding the right information) and **Generation** (writing the correct answer).

---

### 1. Faithfulness
* **Focus Area:** Generator (LLM) Accuracy
* **What it measures:** Factuality and hallucination control.
* **Simple Definition:** Does the generated answer only contain facts that exist in the retrieved documents? 
* **How it works:** It breaks down the generated answer into individual statements and verifies if each statement can be directly inferred from the retrieved contexts. 
* **Why it matters:** A high score (close to **1.0**) means the LLM is not making things up (hallucinating) and is strictly sticking to the provided documents.

---

### 2. Answer Relevancy
* **Focus Area:** Generator (LLM) Quality
* **What it measures:** How directly the generated answer addresses the user's question.
* **Simple Definition:** Does the generated answer actually answer the user's question, or does it go off-topic?
* **How it works:** It analyzes the generated answer, prompts an LLM to guess what question this answer is responding to, and measures how close that guessed question is to the user's actual question.
* **Why it matters:** An answer can be 100% faithful to the text (not hallucinated), but still completely fail to address what the user actually asked. High relevancy means the answer is concise and on-point.

---

### 3. Context Precision
* **Focus Area:** Retrieval System Quality
* **What it measures:** Search ranking quality.
* **Simple Definition:** Are the most relevant chunks of information ranked at the very top of the retrieved results?
* **How it works:** It evaluates whether the retrieved text chunks containing the information needed to answer the question are placed at the beginning of the context window.
* **Why it matters:** LLMs pay more attention to information at the beginning of a prompt. High precision ensures that the most important context isn't buried deep in the text, which prevents the LLM from missing it.

---

### 4. Context Recall
* **Focus Area:** Retrieval System Quality
* **What it measures:** Search completeness.
* **Simple Definition:** Did the search system retrieve *all* the necessary information required to construct the ground-truth answer?
* **How it works:** It compares the ground-truth reference answer against the retrieved context to see if every key point in the ground truth is present in the retrieved texts.
* **Why it matters:** If this score is low, it means the retriever missed crucial parts of the document, making it impossible for the LLM to write a complete and correct answer.

---

### 💡 Quick Reference Summary Table

| Metric | Component Evaluated | Key Inputs Used | What High Score Means |
| :--- | :--- | :--- | :--- |
| **Faithfulness** | Generator (LLM) | Generated Answer + Contexts | **No Hallucinations:** The answer is fully grounded in the retrieved text. |
| **Answer Relevancy** | Generator (LLM) | Question + Generated Answer | **On-Topic:** The answer is direct, concise, and avoids fluff. |
| **Context Precision** | Retriever (Search) | Question + Contexts | **Good Ranking:** The most useful search results are at the top. |
| **Context Recall** | Retriever (Search) | Ground Truth + Contexts | **Complete Search:** The system retrieved all the necessary facts. |

In [12]:
# Calculate the mean for each metric
averages = df_results[["faithfulness", "answer_relevancy", "context_precision", "context_recall"]].mean()

# Convert it to a nice DataFrame for the report
df_averages = averages.to_frame(name="Average Score").reset_index()
df_averages.rename(columns={"index": "Metric"}, inplace=True)

# Format the scores to 4 decimal places for a cleaner look
df_averages["Average Score"] = df_averages["Average Score"].round(4)

# Display the table
print("📊 Evaluation Averages for Report:")
display(df_averages)

# Optionally, save this small table to a CSV as well!
df_averages.to_csv("eval_results/averages.csv", index=False)

📊 Evaluation Averages for Report:

              Metric  Average Score
0       faithfulness         0.8936
1   answer_relevancy         0.8387
2  context_precision         0.8758
3     context_recall         0.9286